services:
  datahandler:
    build:
      context: servierer
    container_name: servierer
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - app-network
    env_file:
      - servierer/.servierenv
    volumes:
      - ./servierer/config.json:/home/serv-it/servierer/config.json:rw
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dblogic:
    build:
      context: db
    container_name: databae
    ports:
      - "127.0.0.1:8001:8000"
    networks:
      - app-network
    env_file:
      - db/.dbenv
    volumes:
      - ./db/checkin_data.db:/home/db-it/databae/checkin_data.db:rw
    depends_on:
      datahandler:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  happy-website:
    build:
      context: website
    container_name: website
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app-network
    depends_on:
      dblogic:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
